springdoc:
  swagger-ui:
    path: /swagger-ui.html

eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}
    healthcheck:
      enabled: true

management:
  health:
    discovery:
      enabled: false
    eureka:
      enabled: false